Iter13
The-Gleb/go_metrics_and_alerting pull request #13
Opened 2023-11-07 21:31 UTC by The-Gleb

2023-11-10 07:33 UTC, edylcrm requested changes

2023-11-10 07:33 UTC, edylcrm commented on cmd/agent/main.go
>  	var wg sync.WaitGroup
[BLOCKER] а зачем здесь осталась wg? Ниже есть цикл который не дает завершить приложение

2023-11-20 22:12 UTC, The-Gleb commented on cmd/agent/main.go
>  	var wg sync.WaitGroup
У меня кстати 13 автотест иногда проходит, а иногда нет. В чем может быть проблема?

2023-11-23 05:39 UTC, edylcrm approved these changes

2023-11-30 13:47 UTC, merged