Iter18
The-Gleb/go_metrics_and_alerting pull request #17
Opened 2024-03-02 12:18 UTC by The-Gleb

2024-03-04 18:40 UTC, s-shpak requested changes
1. Требуется добиться покрытия тестами >= 40%. Пока покрытие составляет 25.2%. См здесь, как это можно рассчитать: https://stackoverflow.com/questions/33444968/how-to-get-all-packages-code-coverage-together-in-go
2. Код необходимо задокументировать ф вормате godoc. См. инкремент 18
4. Неоходимо добавить пример работы с сервиса в `example_test.go`. В нем должен быть пример того, как сервис можно поднять и какие запросы к нему могут делать агенты

2024-03-04 18:40 UTC, s-shpak commented on cmd/server/main.go
> +	// go func() {
Почему ты оставил этот код ? Может его удалить ?

2024-03-04 18:40 UTC, s-shpak commented on Makefile
> +migrateup:
Миграции можно накатывать автоматически при старте сервиса. См. здесь как: https://github.com/s-shpak/webinar-migrations?tab=readme-ov-file#применение-миграций-из-кода

2024-03-09 16:59 UTC, The-Gleb commented on cmd/server/main.go
> +	// go func() {
Не совсем понимаю, что именно и как нужно документировать. Я написал, что делают хендлеры. Остальное как-будто бы кажется и так понятным. Или нет? 
Также, насчет тестов. Я написал тесты для слоя бд или для хендлеров. В тестах хендлеров я ничего не мокал, соответственно, есть ли смысл писать тесты для domain слоя, если он тестируется в тестах хендлеров? При этом в покрытии не отображается, что код domain слоя покрыт.
Насчет example_test.go тоже не очень понял. В файлах с тестами меня есть ExampleXxx() функции для каждого хендлера. Нужно что-то еще помимо этого?
Извиняюсь, что так поздно всё это пишу

2024-03-10 19:40 UTC, s-shpak commented on cmd/server/main.go
> +	// go func() {
1. Вообще, документировать надо что-то, что может использоваться другими пакетами/пользователями. В данном случае того, как ты задокументировал некоторые функции, - вполне достаточно

2024-03-11 10:01 UTC, The-Gleb commented on cmd/server/main.go
> +	// go func() {
1. Понял
2. Да, мне кажется некорректным, что покрытие пакета не отображается, если тесты находятся в другом пакете. По крайней мере команда `go test --cover -v -coverpkg=./... -coverprofile=profile.cov ./...` это не отображала.
Но я сейчас обнаружил, что если запустить `go tool cover -http profile.cov` и посмотреть на профиль покрытия в браузере, то там становится видно, что пакеты service и usecase покрыты, и, кажется, во всем проекте набирается больше 40% покрытия
![image](https://github.com/The-Gleb/go_metrics_and_alerting/assets/115395807/42899803-b726-459d-9b7b-a409d761738f)

Насчет ошибки, странно, у меня ее нет, она была раньше,но я ее пофиксил и сейчас всё работает

3. Хорошо, а где этот файл лучше разместить?

2024-03-11 19:57 UTC, s-shpak requested changes

2024-03-11 19:57 UTC, s-shpak commented on cmd/server/main.go
> +	// go func() {
2. При попытке запуска тестов получаю 
```
Error:      	Received unexpected error:
        	            	failed to connect to `host=localhost user=metric_db database=metric_db`: dial error (dial tcp 127.0.0.1:5434: connect: connection refused)
```

Есть три способа решения: 1. запускать миграции прямо из кода 2. запускать миграции вручную, желательно из докер-контейнера (мэйк-таргет не срабатывает, т.к. `migrate` не установлен на мою машину) 3. оставить все как есть, но добавить инструкции по запуску (впрочем, инструкции по запуску должны быть добавлены в README.md в любом случае, если требуется не просто выполнить `go test ./...`). Как добавить миграции в код мы разбирали на одном из вебинаров: https://github.com/s-shpak/webinar-migrations?tab=readme-ov-file#применение-миграций-из-кода

Есть еще несколько подходов (которые вообще не требуют ручного вмешательства того, кто запускает тесты), но они немного более сложные, можем разобрать при случае, если будет интересно

3. В тех же пакетах, где размещены тесты с примерами сейчас

2024-03-11 19:57 UTC, s-shpak commented on result.bin
Что делает этот файл ?

2024-03-12 11:55 UTC, s-shpak approved these changes

2024-03-12 11:56 UTC, merged