Iter20
The-Gleb/go_metrics_and_alerting pull request #20
Opened 2024-03-10 19:52 UTC by The-Gleb

2024-03-12 19:53 UTC, s-shpak requested changes
По тестам: 1. надо добавить в ридми инструкции по запуску тестов. 2. сейчас тесты падают: во-первых, функция `cleanTables` в `storage_test.go` выбрасывает ошибку о том, что таблицы, которую ты пытаешься почистить не существует; если исправить первую проблему, то получаю такой аутпут команды `go test ./... -v`

[test-output.zip](https://github.com/The-Gleb/go_metrics_and_alerting/files/14577892/test-output.zip)

Поправь все это, пожалуйста, или распиши, как запускать тесты корректно

2024-03-12 19:53 UTC, s-shpak commented on cmd/staticlint/main.go
> +			if d, ok := node.(*ast.FuncDecl); ok &&
1. Попробуй убрать чрезмерую вложенность
2. Необходимо провеить, что вызов происходит из пакета `main`

2024-03-12 19:53 UTC, s-shpak commented on internal/repository/memory/storage_test.go
> +		// TODO: Add test cases.
Вообще, на ревью желательно не отправлять дедкод: если тестов пока нет, то не пиши заглушки для них. Либо помечай PR как WIP (work in progress)

2024-03-12 19:53 UTC, s-shpak commented on internal/repository/database/storage_test.go
> +// func getTestClient(t *testing.T) postgresql.Client {
Все комментарии такого рода - тоже deadcode

2024-03-12 19:53 UTC, s-shpak commented on cmd/staticlint/main.go
> +func run(pass *analysis.Pass) (interface{}, error) {
Добавь, пожалуйста, инструкции о том, как запустить твой анализатор и проверить его (можно в README.md в этой папке)

2024-03-12 22:00 UTC, The-Gleb commented
Всё исправил, только не понимаю, почему у тестов базы данных не получается подключиться к контейнеру, без этого кода 
```
err = pool.Retry(func() error {
      conn, err = pgx.Connect(context.Background(), dsn)
      if err != nil {
	      return fmt.Errorf("failed to connect to the DB: %w", err)
      }
      return nil
})
```

Также почему-то, когда проверяю мультичекером все пакеты ` go run ./cmd/staticlint ./...` или internal `go run ./cmd/staticlint ./internal...` получаю `signal: killed`. При этом, если проверять им cmd или любой пакет внутри internal, то все работает.

2024-03-13 06:58 UTC, s-shpak requested changes
1. Тесты теперь проходят, но покрытие составляет пока 35.4%. См. здесь как рассчитывать: https://stackoverflow.com/a/33457070 . Необходимо повысить покрытие до 55%
2. `staticlint` детектит ряд проблем. Их необходимо поправить. В идеале было бы хорошо добавить более продвинутый линтинг, здесь описано как: https://github.com/s-shpak/praktikum-golangci-lint . На первой части курса я просил всех студентов моей группы добавить линтинг в проект. Если решишь это делать, то настрой еще github actions (в последней секции ридми репозитория описано как). Это, по сути, суперсет текущего линтера.

Прикладываю отчет по покрытию тестами и вывод `staticlint`

[out.zip](https://github.com/The-Gleb/go_metrics_and_alerting/files/14583604/out.zip)

2024-03-14 16:02 UTC, The-Gleb commented
1. https://github.com/The-Gleb/go_metrics_and_alerting/pull/20#issuecomment-1992656409 - эти вопросы всё еще актуальны
2. Как я и говорил раньше, вывод команды `go test --cover -coverprofile profile.cov ./...` не совсем корректен, так как он не показывает покрытие кода, если тесты находятся в другом пакете. Но если запустить тесты командой `go test --cover -coverpkg ./... -coverprofile profile.cov ./...`, а затем посмотреть на репрезентацию профиля покрытия в HTML командой `go tool cover -html profile.cov`, то там видно, что в среднем все файлы, которые должны быть покрыты тестами, покрыты ими более чем на 55%
![image](https://github.com/The-Gleb/go_metrics_and_alerting/assets/115395807/5c53d20f-321b-4deb-a545-d54d30b97804)
![image](https://github.com/The-Gleb/go_metrics_and_alerting/assets/115395807/5da7d773-9803-421e-907d-76284d087376)
4. Проблемы, на которые изначально жаловался мой мультичекер, я исправил. 
Кроме этих. Я не знаю, что с этим делать 
![image](https://github.com/The-Gleb/go_metrics_and_alerting/assets/115395807/179245fa-dd53-4cfd-98d1-72736cdb760c)
5. golangci-lint добавил. Он обнаружил ооочень много проблем. Настолько много, что мне кажется, целесообразнее отключить некоторые линтеры, чем исправлять то, что ему не нравится
   upd: почти всё, что посчитал нужным, исправил, остальные линтеры линтеры убрал из конфига

2024-03-17 09:59 UTC, s-shpak approved these changes

2024-04-17 14:57 UTC, merged