Iter23
The-Gleb/go_metrics_and_alerting pull request #22
Opened 2024-03-17 14:30 UTC by The-Gleb

- Add asymmetric encryption
- Add parsing config from json
- Graceful shutdown on SIGTERM,SIGQUIT,SIGINT

2024-03-17 14:48 UTC, The-Gleb commented
Не понимаю, как правильно установить поле restore в конфиге
cmd/server/config.go:78

2024-03-26 22:54 UTC, s-shpak requested changes

2024-03-26 22:54 UTC, s-shpak commented on cmd/server/config.go
> +// TODO: it is unclear wether 'false' returned by -r flag is default or it was set by flag.
Существует несколько подходов к решению этой проблемы:
1. Анмаршалить bool в `json.RawMessage` (https://pkg.go.dev/encoding/json#RawMessage) и проверять его
2. использовать какую-то библиотеку типа `mergo`, которая под капотом также анмаршалит сообщение в несколько проходов
3. перевернуть флаг (передавать `noRestore` вместо `restore`)

Кажется, что первый вариант наиболее адекватен в данном случае

2024-03-26 22:54 UTC, s-shpak commented on cmd/server/config.go
> +		log.Fatal(err)
Не стоит вызывать `Fatal` из глубины кода: лучше прокинуть ошибку наверх и вызвать из `main`

2024-03-26 22:54 UTC, s-shpak commented on golangci-lint/report.json
Это не стоит пушить в репо

2024-03-26 22:54 UTC, s-shpak commented on golangci-lint/report-unformatted.json
Это не стоит пушить в репо

2024-03-26 22:54 UTC, s-shpak commented on internal/controller/http/v1/middleware/decryption.go
> +		logger.Log.Info("path to private key is empty")
Если логировать это на уровне `Info`, то лог будет забиваться очень быстро. Наверное, стоит выбрать `Debug`

2024-03-26 22:54 UTC, s-shpak commented on internal/controller/http/v1/middleware/decryption.go
> +		// logger.Log.Debugf("request body is %s", string(cipher))
deadcode

2024-03-26 22:54 UTC, s-shpak commented on server
Это не надо пушить

2024-04-01 10:50 UTC, s-shpak approved these changes

2024-04-17 14:57 UTC, merged