Iter5
The-Gleb/go_metrics_and_alerting pull request #5
Opened 2023-10-04 18:31 UTC by The-Gleb

2023-10-06 12:50 UTC, edylcrm requested changes

2023-10-06 12:50 UTC, edylcrm commented on .github/workflows/statictest.yml
> -name: go vet test
Комментарии разделены на несколько типов:
[BLOCKER] - Проблема, не решив которую принять работу нельзя
[LINT] - Заменичение, опционально к выполнению.
[FYI] - просто ремарка

2023-10-06 12:50 UTC, edylcrm commented on cmd/agent/main.go
> +		defer func() { stop <- true }()
[LINT] Вообще конструкция выглядит немного странно. Если хочешь дожидаться когда завершится выполнение горутины лучше использовать sync.WaitGroup. 
Но здесь можно не запускать отдельные две горутины, а просто сделать безконечный цикл:
```
for {
    select {
    case <-pollTicker.C:
        CollectMetrics(gaugeMap, &PollCount)
    case <-reportTicker.C:
	SendMetrics(gaugeMap, &PollCount, client)
}
```

2023-10-06 12:50 UTC, edylcrm commented on cmd/agent/main.go
> +func MakeHTTPCall(URL string) {
[LINT] Зачем нужна эта функция?

2023-10-06 12:50 UTC, edylcrm commented on cmd/server/main.go
> +	err := server.Run()
[FYI] Здесь так же было бы хорошо слушать сигналы ОС и корректно завершать http сервис чтобы пользователи в момент редеплоя приложения или принудительного завершения получили ответ.
Пример работы с сигналами: https://gobyexample.com/signals
Как корректно завершать http сервис: https://pkg.go.dev/net/http#Server.SetKeepAlivesEnabled и https://pkg.go.dev/net/http#Server.Shutdown

2023-10-06 12:50 UTC, edylcrm commented on internal/storage/main.go
> +	gauge   map[string]float64
[FYI] Здесь при записи/чтении может быть race condition

2023-10-06 12:50 UTC, edylcrm commented on internal/storage/main.go
> +	return s.gauge, s.counter
[BLOCKER] Здесь лучше копировать мапы целиком перед отдачей т.к. могут быть проблемы с race condition

2023-10-06 13:05 UTC, edylcrm commented on internal/handlers/main.go
> +	switch mType {
[LINT] Здесь можно воспользоваться дженериками и в storage сделать метод с [T float64 | int64] чтобы каждый раз это не проверять через switch

2023-10-06 13:05 UTC, edylcrm commented on internal/handlers/main.go
> +package handlers
[LINT] и я бы избегал в internal пакете имена файлов main.go, как то не красиво :)

2023-10-08 21:49 UTC, The-Gleb commented on .github/workflows/statictest.yml
> -name: go vet test
Можно, пожалуйста, еще какие-нибудь комментарии по структуре и организации кода? Как сделать лучше?

2023-10-09 05:49 UTC, edylcrm commented on .github/workflows/statictest.yml
> -name: go vet test
Вообще для небольшого проекта структура проекта нормальная. Если есть желание поговорить про структуру и организацию кода записывайся 1-1 :)

2023-10-09 05:51 UTC, edylcrm commented on internal/storage/storage_test.go
> +// func Test_storage_UpdateGauge(t *testing.T) {
А почему закомментировал?

2023-10-09 05:58 UTC, edylcrm requested changes

2023-10-09 05:58 UTC, edylcrm commented on internal/handlers/handlers_test.go
> +// "io"
[BLOCKER] Давай включать тесты :)

2023-10-09 05:58 UTC, edylcrm commented on internal/server/server.go
> +type server struct {
[BLOCKER] Давай методы которые не используются удалим, а те что используются переименуем, чтобы были без цифр

2023-10-09 05:58 UTC, edylcrm commented on cmd/server/main.go
> +	go server.Shutdown(s, c, &wg)
[LINT] Чтобы не передавать waitgroup в функцию shutdown можно написать чуть проще
```
go func() {
    defer wg.Done()
    server.Shutdown(s, c)
}()
```

2023-10-09 20:29 UTC, The-Gleb commented
Написал тесты, и чтобы их пройти немного изменил GetMetric и UpdateMetric методы. Как они? Норм не норм?

2023-10-10 09:51 UTC, edylcrm requested changes

2023-10-10 09:51 UTC, edylcrm commented on internal/storage/storage.go
> +			return http.StatusBadRequest, errors.New("incorrect metric value\ncannot parse to float64")
[LINT] Вообще очень странно, что storage оперирует http статусами о которых он ничего знать не должен. Я бы здесь возвращал 0, errors.New("incorrect metric value\ncannot parse to float64") и на уровне handlers на основании ошибки возвращал нужный статус.

2023-10-10 09:51 UTC, edylcrm commented on cmd/server/main.go
> +	wg.Add(1)
[BLOCKER] А где wg.Waint()?

2023-10-10 09:51 UTC, edylcrm commented on cmd/server/main.go
> +		defer wg.Done()
[BLOCKER] Кажется это будет работать не корректно. В горутине запускается другая горутина и wg.Done() сразу вызывается т.е. от него здесь никакого смысла нет.
Чтобы был смысл надо написать 
```
go func() {
    defer wg.Done()
    server.Shutdonw(s, c)
    
}
```

2023-10-10 10:02 UTC, The-Gleb commented on cmd/server/main.go
> +		defer wg.Done()
Да, действительно, не знаю, почему я так сделал

2023-10-11 07:00 UTC, edylcrm approved these changes

2023-10-11 13:46 UTC, merged